[workspace]
members = [
    "day-10",
    "day-11",
    "day-12",
]
resolver = "2"

[workspace.dependencies]
indoc = "2.0.5"
itertools = "0.13.0"
nom = "7.1.3"
nom_locate = "4.2.0"
miette = { version = "7.4.0", features = ["fancy"] }
rayon = "1.10.0"
thiserror = "2.0.6"
