[package]
name = "day-14"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"

[dependencies]
indicatif.workspace = true
indoc.workspace = true
nom.workspace = true
